version: '3.8'

services:
  auth_db:
    image: postgres:latest
    container_name: auth_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EffectiveMobileAuth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_app:
    container_name: auth_app
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_NAME: EffectiveMobile
      DB_USER: context
      DB_PASSWORD: context

#  -----------------------------------
  task_manager_db:
    image: postgres:latest
    container_name: task_manager_db
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EffectiveMobileTaskManager
      PGPORT: 5433
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  task_manager_app:
    container_name: task_manager_app
    build:
      context: ./TaskManager
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      task_manager_db:
        condition: service_healthy
    environment:
      DB_HOST: task_manager_db
      DB_PORT: 5433
      DB_NAME: EffectiveMobileTaskManager
      DB_USER: context
      DB_PASSWORD: context